In [1]:
cd ..

/home/pauline/Dokumente/Delab_Projekt/delab

In [30]:
from util.sql_switch import get_query_native

tweet_text = get_query_native(
    "SELECT ta.id as author_id, conversation_id, text, screen_name , is_climate_author, climate_author_type FROM delab_tweet t, delab_tweetauthor ta WHERE t.author_id=ta.twitter_id")
tweet_text = tweet_text.loc[tweet_text['is_climate_author']== True]
tweet_text.head()

using postgres

/home/pauline/Dokumente/Delab_Projekt/delab/venv/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,author_id,conversation_id,text,screen_name,is_climate_author,climate_author_type
2,95,1578218562170155009,"We don't need a TV show or movie to tell us that climate change is real. But it certainly helps, and it can spur us to act. \n\nhttps://t.co/fOEkp6kfUK",Greenpeace,True,non-governmental organisation
9,360,1598387957702217728,"Unsere neueste @correctiv_org -Recherche:\nJeder Mensch in der EU bezahlt √ºber Steuern Gelder an milliardenschwere Gro√ükonzerne. .\nWir benennen die gr√∂√üten Empf√§nger:\nS√ºdzucker (gr√∂√üter Zuckerproduzent der Welt)\nFrieslandCampina (Tuffi, Landliebe...)üßµ\nhttps://t.co/l2sdfnXD6o",AnnikaJoeres,True,journalist
62,95,1577040800994983936,For decades Indigenous activists have been sounding the alarm on climate change. But their warnings have too often been ignored. It‚Äôs time for Indigenous voices to lead the climate fight! https://t.co/1QJv7wZaW5,Greenpeace,True,non-governmental organisation
88,1,1578084206940487680,"@COP27P stop excluding African activists, we have a voice that need to be heard. \n\nLet this be an African cop as you mentioned previously.\n\nhttps://t.co/exhbsRIqYA",mnyomb1,True,activist
91,103,1585616351493820416,@mnyomb1 @COP27P @TIME üíöüëç‚úåÔ∏è,parents4future,True,non-governmental organisation

In [12]:
authors = tweet_text.groupby('climate_author_type').count()
authors

                               author_id  text  screen_name  is_climate_author
climate_author_type
activist                              85    85           85                 85
journalist                            24    24           24                 24
non-governmental organisation        113   113          113                113
organisation                          50    50           50                 50
politician                            21    21           21                 21
scientist                            107   107          107                107

In [31]:
tweet_links = tweet_text.loc[tweet_text['text'].str.contains("https://")]
tweet_links.head()

,author_id,conversation_id,text,screen_name,is_climate_author,climate_author_type
2,95,1578218562170155009,"We don't need a TV show or movie to tell us that climate change is real. But it certainly helps, and it can spur us to act. \n\nhttps://t.co/fOEkp6kfUK",Greenpeace,True,non-governmental organisation
9,360,1598387957702217728,"Unsere neueste @correctiv_org -Recherche:\nJeder Mensch in der EU bezahlt √ºber Steuern Gelder an milliardenschwere Gro√ükonzerne. .\nWir benennen die gr√∂√üten Empf√§nger:\nS√ºdzucker (gr√∂√üter Zuckerproduzent der Welt)\nFrieslandCampina (Tuffi, Landliebe...)üßµ\nhttps://t.co/l2sdfnXD6o",AnnikaJoeres,True,journalist
62,95,1577040800994983936,For decades Indigenous activists have been sounding the alarm on climate change. But their warnings have too often been ignored. It‚Äôs time for Indigenous voices to lead the climate fight! https://t.co/1QJv7wZaW5,Greenpeace,True,non-governmental organisation
88,1,1578084206940487680,"@COP27P stop excluding African activists, we have a voice that need to be heard. \n\nLet this be an African cop as you mentioned previously.\n\nhttps://t.co/exhbsRIqYA",mnyomb1,True,activist
123,1,1582639690309828609,"I hope @COP27P is watching these. As it in Africa, this year‚Äôs climate change negotiations should be all about doing not talk and talk.\n\nWe need compensation\nWe need to rebuild.\nWe need to prepare for the worst #ClimateEmergency #lossanddamage https://t.co/99RYL2z9Hy",mnyomb1,True,activist

In [32]:
tweet_mentions = tweet_text.loc[tweet_text['text'].str.contains("@")]
tweet_mentions.head()

,author_id,conversation_id,text,screen_name,is_climate_author,climate_author_type
9,360,1598387957702217728,"Unsere neueste @correctiv_org -Recherche:\nJeder Mensch in der EU bezahlt √ºber Steuern Gelder an milliardenschwere Gro√ükonzerne. .\nWir benennen die gr√∂√üten Empf√§nger:\nS√ºdzucker (gr√∂√üter Zuckerproduzent der Welt)\nFrieslandCampina (Tuffi, Landliebe...)üßµ\nhttps://t.co/l2sdfnXD6o",AnnikaJoeres,True,journalist
88,1,1578084206940487680,"@COP27P stop excluding African activists, we have a voice that need to be heard. \n\nLet this be an African cop as you mentioned previously.\n\nhttps://t.co/exhbsRIqYA",mnyomb1,True,activist
91,103,1585616351493820416,@mnyomb1 @COP27P @TIME üíöüëç‚úåÔ∏è,parents4future,True,non-governmental organisation
123,1,1582639690309828609,"I hope @COP27P is watching these. As it in Africa, this year‚Äôs climate change negotiations should be all about doing not talk and talk.\n\nWe need compensation\nWe need to rebuild.\nWe need to prepare for the worst #ClimateEmergency #lossanddamage https://t.co/99RYL2z9Hy",mnyomb1,True,activist
124,103,1582639690309828609,@dpomondi @mnyomb1 @birgitomo @ECOWARRIORSS @orridge_anna @GlblCtznAfrica @GretaThunberg @GeraldKutney @ClimateBen @liquiddahang @davidrvetter The whole CONTINENT of Africa... just 3% (!)\n\n...see e.g. @_HannahRitchie @OurWorldInData \nhttps://t.co/JExq4YP3yc,parents4future,True,non-governmental organisation

In [33]:
tweet_len = tweet_text
tweet_len['text_length'] = tweet_len['text'].str.len()
tweet_len.head()

,author_id,conversation_id,text,screen_name,is_climate_author,climate_author_type,text_length
2,95,1578218562170155009,"We don't need a TV show or movie to tell us that climate change is real. But it certainly helps, and it can spur us to act. \n\nhttps://t.co/fOEkp6kfUK",Greenpeace,True,non-governmental organisation,149
9,360,1598387957702217728,"Unsere neueste @correctiv_org -Recherche:\nJeder Mensch in der EU bezahlt √ºber Steuern Gelder an milliardenschwere Gro√ükonzerne. .\nWir benennen die gr√∂√üten Empf√§nger:\nS√ºdzucker (gr√∂√üter Zuckerproduzent der Welt)\nFrieslandCampina (Tuffi, Landliebe...)üßµ\nhttps://t.co/l2sdfnXD6o",AnnikaJoeres,True,journalist,274
62,95,1577040800994983936,For decades Indigenous activists have been sounding the alarm on climate change. But their warnings have too often been ignored. It‚Äôs time for Indigenous voices to lead the climate fight! https://t.co/1QJv7wZaW5,Greenpeace,True,non-governmental organisation,211
88,1,1578084206940487680,"@COP27P stop excluding African activists, we have a voice that need to be heard. \n\nLet this be an African cop as you mentioned previously.\n\nhttps://t.co/exhbsRIqYA",mnyomb1,True,activist,163
91,103,1585616351493820416,@mnyomb1 @COP27P @TIME üíöüëç‚úåÔ∏è,parents4future,True,non-governmental organisation,27

In [22]:
author_mention = tweet_mentions.groupby('climate_author_type').count() /authors
author_mention

,author_id,text,screen_name,is_climate_author
climate_author_type,,,,
activist,0.552941,0.552941,0.552941,0.552941
journalist,0.500000,0.500000,0.500000,0.500000
non-governmental organisation,0.451327,0.451327,0.451327,0.451327
organisation,0.280000,0.280000,0.280000,0.280000
politician,0.476190,0.476190,0.476190,0.476190
scientist,0.663551,0.663551,0.663551,0.663551

In [23]:
authors_links = tweet_links.groupby('climate_author_type').count() / authors
authors_links

,author_id,text,screen_name,is_climate_author
climate_author_type,,,,
activist,0.635294,0.635294,0.635294,0.635294
journalist,0.833333,0.833333,0.833333,0.833333
non-governmental organisation,0.716814,0.716814,0.716814,0.716814
organisation,0.740000,0.740000,0.740000,0.740000
politician,0.619048,0.619048,0.619048,0.619048
scientist,0.644860,0.644860,0.644860,0.644860

In [40]:
authors_tweet_len = tweet_len.groupby('climate_author_type').mean()
authors_tweet_len = authors_tweet_len.drop(columns=['author_id', 'is_climate_author', 'conversation_id'])
authors_tweet_len

                               text_length
climate_author_type
activist                        179.393258
journalist                      219.250000
non-governmental organisation   219.745902
organisation                    258.392157
politician                      212.619048
scientist                       177.559633